### ISSUE TITLE
Command `gitfaces` not found

### ISSUE THREAD

**Issue by ferenczy** [nschloe/gitfaces#3]
I have tried to install Gitfaces on both *Python for Windows* and *Python for Cygwin* and in both cases the installation was successful, but the command `gitfaces` doesn't exist for some reason. It simply didn't create the starting script in the `/usr/bin` directory (in the case of Cygwin). Analogously there's not executable in `<python>\Scripts\` in the case of Python for Windows.

So there is no way to execute `gitfaces`.

**Comment by nschloe** [comment]
I've fixed an installation error and uploaded a new version. Should be fixed now.

**Comment by ferenczy** [comment]
It's working now. Thanks.
